from abc import ABCMeta
from apscheduler.events import (
    EVENT_JOB_ERROR as EVENT_JOB_ERROR,
    EVENT_JOB_EXECUTED as EVENT_JOB_EXECUTED,
    EVENT_JOB_MISSED as EVENT_JOB_MISSED,
    JobExecutionEvent as JobExecutionEvent,
)

class MaxInstancesReachedError(Exception):
    def __init__(self, job) -> None: ...

class BaseExecutor(metaclass=ABCMeta):
    def __init__(self) -> None: ...
    def start(self, scheduler, alias) -> None: ...
    def shutdown(self, wait: bool = True) -> None: ...
    def submit_job(self, job, run_times) -> None: ...

def run_job(job, jobstore_alias, run_times, logger_name): ...
async def run_coroutine_job(job, jobstore_alias, run_times, logger_name): ...
