from apscheduler.schedulers.base import BaseScheduler as BaseScheduler, STATE_STOPPED as STATE_STOPPED

class BlockingScheduler(BaseScheduler):
    def start(self, *args, **kwargs) -> None: ...
    def shutdown(self, wait: bool = True) -> None: ...
    def wakeup(self) -> None: ...
