from apscheduler.schedulers.base import BaseScheduler as BaseScheduler
from apscheduler.util import maybe_ref as maybe_ref

def run_in_reactor(func): ...

class TwistedScheduler(BaseScheduler):
    def shutdown(self, wait: bool = True) -> None: ...
    def wakeup(self) -> None: ...
