from _typeshed import Incomplete
from apscheduler.triggers.base import BaseTrigger as BaseTrigger
from apscheduler.util import (
    check_callable_args as check_callable_args,
    convert_to_datetime as convert_to_datetime,
    datetime_repr as datetime_repr,
    get_callable_name as get_callable_name,
    obj_to_ref as obj_to_ref,
    ref_to_obj as ref_to_obj,
)

class Job:
    def __init__(self, scheduler, id: Incomplete | None = None, **kwargs) -> None: ...
    def modify(self, **changes): ...
    def reschedule(self, trigger, **trigger_args): ...
    def pause(self): ...
    def resume(self): ...
    def remove(self) -> None: ...
    @property
    def pending(self): ...
    def __eq__(self, other): ...
