from _typeshed import Incomplete

__all__ = [
    "asint",
    "asbool",
    "astimezone",
    "convert_to_datetime",
    "datetime_to_utc_timestamp",
    "utc_timestamp_to_datetime",
    "datetime_ceil",
    "get_callable_name",
    "obj_to_ref",
    "ref_to_obj",
    "maybe_ref",
    "check_callable_args",
    "normalize",
    "localize",
    "undefined",
]

class _Undefined:
    def __nonzero__(self): ...
    def __bool__(self) -> bool: ...

undefined: Incomplete

def asint(text): ...
def asbool(obj): ...
def astimezone(obj): ...
def convert_to_datetime(input, tz, arg_name): ...
def datetime_to_utc_timestamp(timeval): ...
def utc_timestamp_to_datetime(timestamp): ...
def datetime_ceil(dateval): ...
def get_callable_name(func): ...
def obj_to_ref(obj): ...
def ref_to_obj(ref): ...
def maybe_ref(ref): ...
def check_callable_args(func, args, kwargs) -> None: ...
def normalize(dt): ...
def localize(dt, tzinfo): ...
