from .json import jsonify as jsonify

def get_scheduler_info(): ...
def pause_scheduler(): ...
def resume_scheduler(): ...
def start_scheduler(): ...
def shutdown_scheduler(): ...
def add_job(): ...
def delete_job(job_id): ...
def get_job(job_id): ...
def get_jobs(): ...
def update_job(job_id): ...
def pause_job(job_id): ...
def resume_job(job_id): ...
def run_job(job_id): ...
