from .utils import bytes_to_wsgi as bytes_to_wsgi, wsgi_to_bytes as wsgi_to_bytes
from _typeshed import Incomplete

def get_authorization_header(): ...

class Authorization(dict):
    auth_type: Incomplete
    def __init__(self, auth_type, **kwargs) -> None: ...

class HTTPAuth:
    def get_authorization(self) -> None: ...
    def get_authenticate_header(self) -> None: ...

class HTTPBasicAuth(HTTPAuth):
    www_authenticate_realm: str
    def get_authorization(self): ...
    def get_authenticate_header(self): ...
