def job_to_dict(job): ...
def pop_trigger(data): ...
def trigger_to_dict(trigger): ...
def fix_job_def(job_def) -> None: ...
def extract_timedelta(delta): ...
def bytes_to_wsgi(data): ...
def wsgi_to_bytes(data): ...
