# rename this to env.py

SPOTIFY_APP_ID = "PLACEHOLDER_VALUE"
SPOTIFY_APP_SECRET = "PLACEHOLDER_VALUE"
SPOTIFY_REFRESH_TOKEN = "PLACEHOLDER_VALUE"

USER_CONFIG_MODULE = "DeviceGroup.Name"  # replace "Name" with Jan/Kjeld
